### PR TITLE
expanding verbose remotes, pull commands; excise distributed

### PR DESCRIPTION
**Pull request by randomecho**
- verbosity - show how to see details of remotes
  added and not just the aliases, and that note
  about how you can have different fetch/push urls
- noun also a verb - in the use of clone as a verb,
  we can gut right into the sentence
- nip & tuck - some sentences just used too many
  of the same words, really stemming flow
- pull - deliver on the tease and mention what magic
  will be made with this hand-wavy command
- "distributed" already covered by "remotes", so there didn't seem like a reason for it to stick around, especially when it was already using the same chunk of remotes

### CODE REVIEW

**Comment by matthewmccullough** [comment]
I'm totally cool with all the wording changes. I merely want to pause and ask @tlberglund what he thinks about the removal of the distributed part.  I certainly don't think it need to duplicate the use of the same remotes, but I have a little affinity for the prose that describes why we care about distributed. Do you think that any of that "prelude" text in `distributed` should be brought into `remotes`?

**Comment by randomecho** [comment]
Was thinking it might also do better to describe what the difference is with distributed in "intro" but re-reading it, it's quite heavy enough currently with new information to someone coming in clean to the Git way of things.

**Comment by tlberglund** [comment]
I'm going to keep the `distributed` document in there. I'll merge this locally, then restore the file out of the previous commit. Thanks again for your edits, @randomecho! Keep 'em coming.

**Comment by randomecho** [comment]
Neato. Was ready to re-submit the PR should it be rejected on the account of that file.

**Comment by tlberglund** [comment]
Hey, we know how to use the Git here. :)

**Pull request merged**
