### PR TITLE
Skips regenerating the index against template, stay on sketchy cogs

### PR DESCRIPTION
**Pull request by randomecho**
This just guts out a chunk of Rakefile, not sure if it was too much though.

Normally when you regen via rake it throws in the index and births out this thing you don't actually see on the live site. That can throw you. Well, it did personally when first patching the site.

Spurred by #29

### CODE REVIEW

**Comment by matthewmccullough** [comment]
@brntbeer if you have a moment, could you put :eyes: on this and tell me if it looks good to go to at least maintain this page until we unify it with all the training materials?

**Comment by brntbeer** [comment]
I'm on it!

**Comment by matthewmccullough** [comment]
This is going be superseded #37

**Comment by brntbeer** [comment]
@randomecho since my latest merge, can we just drop this PR completely? I'll leave it to you to close it.

**Comment by randomecho** [comment]
Nubbins :thumbsup:

**Pull request closed without merging**
