### PR TITLE
100% width on container class to help with split screen viewing

### PR DESCRIPTION
**Pull request by noslouch**
Hi - I was studying the site and following along in my terminal, but I had to shrink my browser so both windows would fit on my screen. I found it easier to read both after changing the container class width to 100%, so the text wouldn't overflow beyond the viewport.

Figured other people might find it useful too...

Great site!
Brian

### CODE REVIEW

**Comment by randomecho** [comment]
Looks like undoing the sketchy cogs version of the landing page (index.html) has been caught up in this commit with one that was meant for a while back.

**Comment by noslouch** [comment]
:-/ I raked it according to the README, but maybe that wasn't right? Still new to git... not sure what my next step should be.

**Comment by randomecho** [comment]
Don't worry too much about that. Easy to be caught by.

Rake, most of the time, only really needs to be run for any changes to the templates or pages which will affect the generated pages in /p and the index.html itself. A tweak only on the CSS file should get away without it.

**Comment by noslouch** [comment]
Cool. Thanks.

So should I trash this pull request and do it again with just the CSS file?

**Comment by randomecho** [comment]
That (a new PR) sounds cleaner than committing a revert or redo of the index.html with this current pull request. But whatever you feel comfortable with.

**Pull request closed without merging**
