### PR TITLE
Regenerating pages with new Youtube links. Sure seems like a lot of content change though.

### PR DESCRIPTION
**Pull request by matthewmccullough**

### CODE REVIEW

**Comment by matthewmccullough** [comment]
@randomecho Do you trust this as a regen of #27? Seems like a lot of change.

**Comment by randomecho** [comment]
This does look like #27 again, but with a different landing page. Why does it diff the entire /p/ pages anyhow?

The live index.html just isn't at all what you get when you run `rake`, have been meaning to raise that issue too.

**Comment by randomecho** [comment]
Looks like you only really need to regenerate for intro and setup (didn't realise they weren't committed as part of #27 until now), leaving the index with cogs.

**Comment by matthewmccullough** [comment]
Visually "diffed" all the files in the browser. Looks good to go. Merging so we can have fixed videos.

**Pull request merged**
