### PR TITLE
Jekyllify

### PR DESCRIPTION
**Pull request by brntbeer**
Certainly a work in progress, but all links through the pages currently work.

There's a few pages that aren't anyone in the "course"
- customizing
- stashing
- Screencast
- amending
- distributed

I'd think distributed needs removed since it's empty and i would think this is more of an "extended learning" to a book (git-scm.com)

Amending i'll probably add front-matter, no idea where to add it though.

Screencast seems like a good thing to put after git-scm.md because it's an "additional resources" page.

Stashing also feels pretty essential that needs flushed out and written.

Customizing needs worked on, looks like a good "oh and heres how to add aliases!"

### CODE REVIEW

**Comment by brntbeer** [comment]
To test this:

```
git clone https://github.com/github/learn.github.com
git checkout jekyllify
bundle
jekyll --server
```

Then just go to `localhost:4000` or `localhost:4000/p/intro.md` and get started following through the course.

**Comment by matthewmccullough** [comment]
Testing this now.

**Comment by matthewmccullough** [comment]
I'd be all +1 for shipping this when you are fine with it as a "migration" and breaking your more in-depth top-of-the-pull-request content polish ideas into separate iterations.

I went through this locally on localhost:4000/p

My only final thought would be to add a better index.html that re-enables this.  Maybe even turn intro.html into index.html and let it be "live" again.

**Comment by brntbeer** [comment]
Good call on changing intro.html to index.html. Also want to put a
"additional reading" as the last item. Will work on this now. Thanks!

On Mon, Mar 25, 2013 at 2:42 PM, Matthew McCullough <
notifications@github.com> wrote:

> I'd be all +1 for shipping this when you are fine with it as a "migration"
> and breaking your more in-depth top-of-the-pull-request content polish
> ideas into separate iterations.
> 
> I went through this locally on localhost:4000/p
> 
> My only final thought would be to add a better index.html that re-enables
> this. Maybe even turn intro.html into index.html and let it be "live" again.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/learn.github.com/pull/37#issuecomment-15427525
> .

## 

Brent Beer
GitHub:Training
http://training.github.com
https://github.com/brntbeer

**Comment by matthewmccullough** [comment]
I like these last changes.  :shipit:

**Comment by brntbeer** [comment]
Here we go!

**Pull request merged**
