### PR TITLE
Compress images

### PR DESCRIPTION
**Pull request by pathawks**
Compress images using [ImageOptim](https://github.com/pornel/ImageOptim) version 1.4.3

### CODE REVIEW

**Comment by brntbeer** [comment]
hey @pathawks can you describe the change that occurred in this?

**Comment by pathawks** [comment]
There should be no change to the _pixel_ data of the image.

[ImageOptim](http://imageoptim.com/) performs a number of lossless quality algorithms, such as removing unused colors from the index, and trying a number of different optimized GZIP routines such as [zopfli](https://code.google.com/p/zopfli/)

**Comment by brntbeer** [comment]
based on @cobyism's double checking (https://github.com/github/choosealicense.com/pull/81#issuecomment-22946325) im going to merge this.

**Comment by brntbeer** [comment]
Also, i should note that this repo is deprecated as well

**Pull request merged**
