### PR TITLE
Redirect lessons

### PR DESCRIPTION
**Pull request by brntbeer**
Shoutout @cobyism for having an amazingly easy OSS project that allowed me to throw together this landing page with literally 0 headaches.

also, cc @github/training-team, checkout to this branch, run `script/bootstrap` and `jekyll serve` and tell me what you think.

screen shot 2013-06-29 at 4 57 23 pm

### CODE REVIEW

**Comment by jordanmccullough** [comment]
Thanks @brntbeer! Let me dabble with a few CSS tweaks and then I think we're ready to :ship:--if the rest of the teams says so.

**Comment by brntbeer** [comment]
Thanks @jordanmccullough ! what css tweaks did you have in mind? I'm kinda dead set on the font types, the `<a>` tag color, and the footer look :sweat_smile: but could be convinced.

Only reason i'm overly sensitive on it is because it actually took me a while and i was pretty pumped once i got Gridism to work! But, your css skills being :muscle: than mine, I could be convinced otherwise of things!

**Comment by jordanmccullough** [comment]
The only three adjustments (css/content) I was going to tweak are listed below.

Thanks for getting the work so far done and underway to ship!

1) Header size (the awesome GH YouTube banner) to match the content pane width
2) "The content is currently deprecated, but Don't Panic!" on a separate line from the rest of the description for clarity.
3) Adding the GH traditional footer, something like the attachment below.

screen shot 2013-07-01 at 3 54 22 pm

**Comment by brntbeer** [comment]
oh, yeah that all sounds fine.

Did you just change the background color on the footer? looks nearly the same, either way :ship: :shipit:

**Comment by brntbeer** [comment]
annnnd thanks! good eye ;)

**Comment by jordanmccullough** [comment]
Let me get my :paw_prints: on this tomorrow (07-02-13), and if I fall through on that proposed timeframe, let's just :ship: it the way it is. Deal? :smile:

**Comment by matthewmccullough** [comment]
Looks super @brntbeer!  I really, really appreciate your polish on working to unify our content.  Every. Little. Step.  Helps.

My only quick pre-ship note is that Help, Speakerdeck and Talks can support HTTPS now, and I love running as many things HTTPS as possible (good idea? bad idea?).

**Comment by jordanmccullough** [comment]
@brntbeer, Take a look at the tiny tweaks I did--hopefully they help out with the minor refinements.

This has my :+1: for :ship:ing this.

**Comment by jordanmccullough** [comment]
@matthewmccullough Updated the URLs as you suggested.

**Comment by brntbeer** [comment]
Thanks for theURL fixes jordan! checking out new look now

**Comment by brntbeer** [comment]
:+1: @jordanmccullough

**Pull request merged**
