### PR TITLE
move gitcasts videos to be embedded at top of the screen

### PR DESCRIPTION
**Pull request by brntbeer**
Missing from Learn:
- Interactive Add
- Git Browsing
- Creating Empty Branches

Missing Videos:
- Reset
- Tagging
- git-svn

### CODE REVIEW

**Comment by brntbeer** [comment]
Also this will help us kill off gitcasts if we can get everything on learn.github.com

**Comment by matthewmccullough** [comment]
How do you feel about me merging this @github/training-team and @brntbeer ?

**Comment by jordanmccullough** [comment]
The `center` tag was deprecated in HTML "4.0". Might we just fix that up, use a class with `margin: auto auto` instead? Just for syntax tidiness sake?

Edit:
Alternatively, we could use a selector that applies `display: inline-block; text-align: center`.

**Comment by brntbeer** [comment]
@jordanmccullough if you want to make those changes, go for it on this branch before we merge, otherwise i can get to it tonight or tomorrow morning.

@matthewmccullough before merging this, What do you think about replacing some of the videos (setup, normal workflow, branching and merging, log) with your links? I'd like to keep as much up to date info as possible

**Comment by jordanmccullough** [comment]
CSS class and centering on its way! :smile:

**Comment by jordanmccullough** [comment]
Removed all deprecated `<center>` tags and added CSS tag+attribute selector for styling-centering-scaling YouTube video embeds.

All YouTube videos now scale up to default YouTube sizes of 790x430px, but scale down if the browser is smaller. Screenshots show effect:

screen shot 2013-05-07 at 1 38 17 pm
screen shot 2013-05-07 at 1 38 22 pm

**Comment by jordanmccullough** [comment]
This PR is ready for approval, now with @brntbeer's adjustments to the video placement and the centering styles I just pushed. Let's :ship: it.

**Comment by brntbeer** [comment]
awesome! thanks for the merge Matthew and the additional work Jordan!

**Pull request merged**
